In [2]:
import numpy as np


In [3]:
a = np.array(13) #array de dimensión 0
print("type(a):", type(a), "\n")
print("a:", a, sep = "\n")
a
b = np.array([1, 2, 3, 4]) #array de dimensión 1
print("b:", b, sep = "\n")
b
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #array de dimensión 2
print("c:", c, sep = "\n")
c
d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]) #array de dimensión 3
print("d:", d, sep = "\n")
d

type(a): <class 'numpy.ndarray'> 

a:
13
b:
[1 2 3 4]
c:
[[1 2 3 4]
 [5 6 7 8]]
d:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [5]:
# el tamaño de los arreglos es diferente a su dimension. 
#podemos cambiar la forma, osea aumentar dimensiones o numero de elementos por dimensión

print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


In [6]:
print("c =", c, "\n") # c = [[1 2 3 4][5 6 7 8]]
c_1D = c.reshape(1, 8)
print("c_1D =", c_1D, "\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 



In [7]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [8]:
try:
    d.reshape(3,5)
except:
    print('Hay un error al intentar cambiar la forma del arreglo')


Hay un error al intentar cambiar la forma del arreglo


In [9]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

Para no especificar explícitamente el número de elementos de una (solamente una) de las dimensiones se le puede dar el valor -1 (solamente una vez) al método reshape().

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# operaciones con vectores:
vector = np.array([1,2,3,4,5,6,7,8,9])
indx = np.where(vector%3 == 0)
print(f'`type(indx)`:\t{type(indx)}')
print(f'`indx`:\t{indx}')

`type(indx)`:	<class 'tuple'>
`indx`:	(array([2, 5, 8]),)


In [13]:
import pandas as pd

In [15]:
counties = pd.read_excel("https://github.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/blob/main/Python/Datos/counties.xlsx?raw=true")

In [16]:
a = np.array([1,2,3])

In [18]:
b = np.array([[1,2,3],[4,5,6]])